name: Build and Release Chrome Extension

on:
  push:
    tags:
      - 'v*.*.*'  # This pattern matches tags like v1.0.0, v20.15.10, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Create CRX File
      uses: notlmn/browser-extension-release-action@v1
      with:
        extension-root: ./dist  # Adjust if your build outputs to a different directory
        artifact-name: 'extension-${{ github.ref_name }}.crx'
        export-crx: true
      env:
        CRX_PRIVATE_KEY: ${{ secrets.CRX_PRIVATE_KEY }}

    - name: Upload CRX Artifact to GitHub Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: './extension-${{ github.ref_name }}.crx'
        asset_name: 'extension-${{ github.ref_name }}.crx'
        asset_content_type: 'application/x-chrome-extension'