name: Build and Release Chrome Extension

on:
  push:
    tags:
      - 'v*.*.*'  # This pattern matches tags like v1.0.0, v20.15.10, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    # pack zip and read manifest, can be reused in the following steps
    - id: packExtensionDir
      uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
      with:
        extensionDir: 'extension'
        zipFilePath: 'build/extension-${{ github.ref_name }}.zip'

    - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
      with:
        # zip file made at the packExtensionDir step
        zipFilePath: 'build/extension-${{ github.ref_name }}.zip'
        crxFilePath: 'build/extension-${{ github.ref_name }}.crx'
        privateKey: ${{ secrets.CRX_PRIVATE_KEY }}
        # The following is optional if you need update.xml file
        # updateXmlPath: 'build/update.xml'
        # updateXmlCodebaseUrl: 'https://server.com/extension.crx'

    - name: Upload CRX Artifact to GitHub Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: './extension-${{ github.ref_name }}.crx'
        asset_name: 'extension-${{ github.ref_name }}.crx'
        asset_content_type: 'application/x-chrome-extension'